export const SHORTS = [
  {
    uploader: "KY",
    thumbnail: "defaultThumbnail.jpg",
    name: "Learn What Matters for You",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "1:07",
    views: "590",
    uploadTime: "few seconds",
  },
  {
    uploader: "RS",
    thumbnail: "defaultThumbnail.jpg",
    name: "Create your own Jarvis",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "1:05",
    views: "12k",
    uploadTime: "10 hours",
  },
  {
    uploader: "TP",
    thumbnail: "defaultThumbnail.jpg",
    name: "How to make a bootable pendrive",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "10",
    views: "230",
    uploadTime: "1 year",
  },
  {
    uploader: "CW",
    thumbnail: "defaultThumbnail.jpg",
    name: "How to make a cake at Home?",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "59",
    views: "1k",
    uploadTime: "5 hours",
  },
  {
    uploader: "MV",
    thumbnail: "defaultThumbnail.jpg",
    name: "#Project 1 Create a youtube clone",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "30",
    views: "1M+",
    uploadTime: "2 years",
  },
  {
    uploader: "CS",
    thumbnail: "defaultThumbnail.jpg",
    name: "Hello World in python",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "20",
    views: "1k",
    uploadTime: "2 hours",
  },
  {
    uploader: "CD",
    thumbnail: "defaultThumbnail.jpg",
    name: "Create your own LLM",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "30",
    views: "1k",
    uploadTime: "2 hours",
  },
  {
    uploader: "RM",
    thumbnail: "defaultThumbnail.jpg",
    name: "Create a server image",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "10",
    views: "10k",
    uploadTime: "2 years",
  },
  {
    uploader: "DR",
    thumbnail: "defaultThumbnail.jpg",
    name: "Learn Next Js",
    desc: "This is the description of the video with random text. This will be shown below the name",
    duration: "49",
    views: "100k",
    uploadTime: "2 years",
  },
];
