version: "3"

services:
  redis:
    image: redis:latest
    container_name: video-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - video-redis-network

volumes:
  redis-data:
    driver: local

networks:
  video-redis-network:
    driver: bridge
